# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_diversity_Cpp <- function(D, knn_idx, batch_labels, n_batches, perplexity = 15, tol = 1e-5) {
    .Call('_sndiversity_compute_diversity_Cpp', PACKAGE = 'sndiversity', D, knn_idx, batch_labels, n_batches, perplexity, tol)
}

