# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

inPlaceRankMean <- function(v_temp, idx_begin, idx_end) {
    .Call('_wilcoxauc_inPlaceRankMean', PACKAGE = 'wilcoxauc', v_temp, idx_begin, idx_end)
}

inPlaceRankMin <- function(v_temp, idx_begin, idx_end) {
    .Call('_wilcoxauc_inPlaceRankMin', PACKAGE = 'wilcoxauc', v_temp, idx_begin, idx_end)
}

rank_vec <- function(x, p, nrow, ncol, method) {
    .Call('_wilcoxauc_rank_vec', PACKAGE = 'wilcoxauc', x, p, nrow, ncol, method)
}

sumGroups <- function(x, p, i, ncol, groups, ngroups) {
    .Call('_wilcoxauc_sumGroups', PACKAGE = 'wilcoxauc', x, p, i, ncol, groups, ngroups)
}

nnzeroGroups <- function(p, i, ncol, groups, ngroups) {
    .Call('_wilcoxauc_nnzeroGroups', PACKAGE = 'wilcoxauc', p, i, ncol, groups, ngroups)
}

sumGroupsT <- function(x, p, i, ncol, nrow, groups, ngroups) {
    .Call('_wilcoxauc_sumGroupsT', PACKAGE = 'wilcoxauc', x, p, i, ncol, nrow, groups, ngroups)
}

nnzeroGroupsT <- function(x, p, i, ncol, nrow, groups, ngroups) {
    .Call('_wilcoxauc_nnzeroGroupsT', PACKAGE = 'wilcoxauc', x, p, i, ncol, nrow, groups, ngroups)
}

